name: LaTeX
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Setup TeXLive
      uses: DanySK/setup-texlive-action@0.1.1
    - name: Typeset Project Plan
      run: make -C doc/projectplan
    - name: Typeset Thesis
      run: make -C doc/thesis
