name: LaTeX
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup TeXLive
      uses: DanySK/setup-texlive-action@0.1.1
      with:
        requirements-file: .github/texlive/packages.tex
